API_KEY="AIzaSyBEjvAMTg70W6oUvWc5HzYUS3O9rzEI9Jw"
pdfcrowduser="agaviriaj"
pdfcrowdpass="ff60721e6cd397590c07eca9d5d71f0b"
user_bigdata="admin"
password_bigdata="Aa12345678"
host_bigdata="data-proyect.cbpqfqlu2upq.us-east-2.rds.amazonaws.com"
host_bigdata_lectura="data-proyect-lectura.cbpqfqlu2upq.us-east-2.rds.amazonaws.com"
schema_bigdata="bigdata"
ACCESS_KEY_digitalocean="DO00JMM7DR78LD2JAAEA"
SECRET_KEY_digitalocean="BxBRkj7i5D9TaWkV+CHeji7RKcCNz8myLsndmRadOyQ"
REGION_digitalocean="nyc3"
BUCKET_NAME_digitalocean="prediales"
COGNITO_USER_POOL_ID="us-east-2_Fpda5LMX0"
COGNITO_CLIENT_ID="5kvmdd29oj2lpnq9b4j60gfe69"
