API_KEY="AIzaSyBEjvAMTg70W6oUvWc5HzYUS3O9rzEI9Jw"
pdfcrowduser="agaviriaj"
pdfcrowdpass="ff60721e6cd397590c07eca9d5d71f0b"
user_bigdata="admin"
password_bigdata="Aa12345678"
host_bigdata="data-proyect.cbpqfqlu2upq.us-east-2.rds.amazonaws.com"
host_bigdata_lectura="data-proyect-lectura.cbpqfqlu2upq.us-east-2.rds.amazonaws.com"
schema_bigdata="bigdata"
user_write_urbex="admin"
password_write_urbex="H98gTyitK8afV5tGCAba"
host_read_urbex="urbex-read.czg2uaagg64r.us-east-2.rds.amazonaws.com"
host_write_urbex="urbex.czg2uaagg64r.us-east-2.rds.amazonaws.com"
schema_write_urbex="bigdata"
ACCESS_KEY_digitalocean="DO00JMM7DR78LD2JAAEA"
SECRET_KEY_digitalocean="BxBRkj7i5D9TaWkV+CHeji7RKcCNz8myLsndmRadOyQ"
REGION_digitalocean="nyc3"
BUCKET_NAME_digitalocean="prediales"
COGNITO_USER_POOL_ID="us-east-2_Fpda5LMX0"
COGNITO_CLIENT_ID="5kvmdd29oj2lpnq9b4j60gfe69"
pdf_client_id_1="1808ca6ed472427c8d772e2a30164f77"
pdf_client_secret_1="p8e-MK08vM12OyuL9CkN3FPTWQ13iXTr2-MB"
pdf_email_1="agaviria@buydepa.com"
pdf_client_id_2="ac92415fe1294baa8c318dc195622c2c"
pdf_client_secret_2="y6jHRtpZHAYHeaOQWbpAMMdyo6rUokpX"
pdf_email_2="alejandro@urbex.com.co"